### PR TITLE
contact us page

### PR DESCRIPTION
**Pull request by anushka530**
changed the layout of contact us page corrected the mistakes. Kept layout color in blue and white as per the color of logo.

https://user-images.githubusercontent.com/72335206/112730941-c0ade980-8f0a-11eb-816c-25fa72a990c7.mp4
  
please check and review it . If any changes required please tell.

### CODE REVIEW

**Comment by Rittik-Biswal2000** [comment]
Please resolve the conflicts

**Comment by AltamasBari** [comment]
Replace the contact number with the email id of DSC VSSUT: dscvssutburla@gmail.com

**Comment by anushka530** [comment]
how to resolve this . I am not getting please help

**Comment by anushka530** [comment]
sir , I have done accordingly please review it.

**Comment by etamys** [comment]
it's look good

**Pull request merged**
