### PR TITLE
Label name added in the app

### PR DESCRIPTION
**Pull request by TanuSharma19**
i have added the label name in all the pages of the app .

https://user-images.githubusercontent.com/78946064/111037501-55641200-844a-11eb-9255-61e123e15b38.mp4

### CODE REVIEW

**Comment by Rittik-Biswal2000** [comment]
Is the app working correctly ?

**Comment by AltamasBari** [comment]
#20

**Comment by TanuSharma19** [comment]
Yes sir app is working correctly

**Comment by Rittik-Biswal2000** [comment]
Please create pull request from a new branch

**Comment by TanuSharma19** [comment]
Ohk sir i will do it

**Pull request closed without merging**
