### PR TITLE
Logout Feature added

### PR DESCRIPTION
**Pull request by tanishq-123**
Fixed issue #25 
Logout feature added in homepage

### CODE REVIEW

**Comment by Rittik-Biswal2000** [comment]
Please include a video of your implementation

**Comment by tanishq-123** [comment]
sure, do have a look- [https://drive.google.com/file/d/1CaJmb0MnQ6vt_Lq-4jDh8xWAlLAOclPG/view?usp=sharing](url)

**Comment by tanishq-123** [comment]
https://user-images.githubusercontent.com/55457071/111738643-b3a84f00-88a7-11eb-9ae3-7ea74bcaac6a.mp4

**Comment by Rittik-Biswal2000** [comment]
@tanishq-123  Please resolve conflicts

**Pull request closed without merging**
